# Generated by Django 5.0 on 2025-11-08 03:08

from django.db import migrations

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
    ]

    
def forwards_func(apps, schema_editor):
    ServiceTemplate = apps.get_model('api', 'ServiceTemplate')
    ServiceTemplate.objects.create(
        name="Flask + React Prototyper",
        template_key="flask_react_base",
        description="Un template agile per API Flask e UI React."
    )
    ServiceTemplate.objects.create(
        name="Data Science Notebook",
        template_key="data_science_base",
        description="Un ambiente Jupyter/Flask per analisi dati."
    )