# Generated by Django 5.0 on 2025-11-15 22:53

from django.db import migrations
from django.contrib.postgres.operations import CryptoExtension # <--- ADD THIS IMPORT

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20251108_0308'),
    ]
    operations = [
        CryptoExtension(),
    ]