# Generated by Django 5.0 on 2025-11-23 23:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_serviceinstance_access_path_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceinstance',
            options={'verbose_name': 'Service Instance', 'verbose_name_plural': 'Service Instances'},
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='service_type',
            field=models.CharField(blank=True, help_text='Nome della cartella del Blueprint nel catalogo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='url_prefix',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceinstance',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_instances', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='serviceinstance',
            name='state_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddIndex(
            model_name='serviceinstance',
            index=models.Index(fields=['url_prefix'], name='api_service_url_pre_37266a_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceinstance',
            index=models.Index(fields=['owner', 'service_type'], name='api_service_owner_i_e993b8_idx'),
        ),
        migrations.AlterModelTable(
            name='serviceinstance',
            table='api_serviceinstance',
        ),
    ]
