# Generated by Django 5.0 on 2026-01-29 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_serviceinstance_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinstance',
            name='is_free_tier',
            field=models.BooleanField(default=False, help_text='If checked, this service is available to public visitors without login.'),
        ),
    ]
