# Generated by Django 5.0 on 2026-03-08 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_serviceinstance_is_free_tier'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinstance',
            name='app_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
