# Generated by Django 5.0 on 2026-03-09 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_serviceinstance_app_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicetemplate',
            name='default_app_data',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
