# Generated by Django 5.0 on 2026-03-09 08:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_servicetemplate_default_app_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Es. My Data App', max_length=100)),
                ('app_slug', models.SlugField(help_text='Deve corrispondere al nome cartella in 6_service_catalog', max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_state_config', models.JSONField(blank=True, default=dict)),
                ('default_app_data', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='serviceinstance',
            name='api_service_owner_i_e993b8_idx',
        ),
        migrations.RemoveField(
            model_name='serviceinstance',
            name='description',
        ),
        migrations.RemoveField(
            model_name='serviceinstance',
            name='service_slug',
        ),
        migrations.RemoveField(
            model_name='serviceinstance',
            name='service_type',
        ),
        migrations.RemoveField(
            model_name='serviceinstance',
            name='template',
        ),
        migrations.RemoveField(
            model_name='servicetemplate',
            name='default_app_data',
        ),
        migrations.RemoveField(
            model_name='servicetemplate',
            name='default_state_config',
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='tech_stack',
            field=models.CharField(blank=True, help_text='e.g., React, Vite, Tailwind', max_length=255),
        ),
        migrations.AlterField(
            model_name='serviceinstance',
            name='name',
            field=models.CharField(help_text="Nome personalizzato dall'utente", max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceinstance',
            name='url_prefix',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='name',
            field=models.CharField(help_text='e.g., React Vite Base', max_length=255),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='template_key',
            field=models.SlugField(help_text='Must match folder in 3_service_templates', max_length=255, unique=True),
        ),
        migrations.AddField(
            model_name='serviceapp',
            name='template_source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_apps', to='api.servicetemplate'),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='app',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='api.serviceapp'),
        ),
        migrations.AddIndex(
            model_name='serviceinstance',
            index=models.Index(fields=['owner', 'app'], name='api_service_owner_i_4a7c68_idx'),
        ),
    ]
