# Generated by Django 5.0 on 2026-03-09 08:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_serviceapp_and_more'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceapp',
            name='allowed_groups',
            field=models.ManyToManyField(blank=True, related_name='available_apps', to='auth.group'),
        ),
        migrations.AddField(
            model_name='serviceapp',
            name='owners',
            field=models.ManyToManyField(blank=True, related_name='owned_blueprints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='GroupBusinessRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_instances_per_user', models.IntegerField(default=1, help_text='Quante istanze attive può avere ogni utente in questo gruppo')),
                ('can_access_premium_templates', models.BooleanField(default=False)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business_rule', to='auth.group')),
            ],
        ),
    ]
