# Generated by Django 5.0 on 2026-03-09 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_serviceapp_allowed_groups_serviceapp_owners_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupbusinessrule',
            name='group',
        ),
        migrations.RemoveField(
            model_name='serviceapp',
            name='allowed_groups',
        ),
        migrations.RemoveField(
            model_name='serviceapp',
            name='owners',
        ),
        migrations.RemoveField(
            model_name='serviceapp',
            name='template_source',
        ),
        migrations.RemoveField(
            model_name='serviceinstance',
            name='app',
        ),
        migrations.RemoveIndex(
            model_name='serviceinstance',
            name='api_service_owner_i_4a7c68_idx',
        ),
        migrations.RemoveField(
            model_name='serviceinstance',
            name='app_data',
        ),
        migrations.RemoveField(
            model_name='servicetemplate',
            name='tech_stack',
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='service_slug',
            field=models.SlugField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='service_type',
            field=models.CharField(blank=True, help_text='Nome della cartella del Blueprint nel catalogo', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='serviceinstance',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='instances', to='api.servicetemplate'),
        ),
        migrations.AddField(
            model_name='servicetemplate',
            name='default_state_config',
            field=models.JSONField(blank=True, default=dict, help_text='La configurazione JSON di default per le nuove istanze.'),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='serviceinstance',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='serviceinstance',
            name='url_prefix',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='servicetemplate',
            name='template_key',
            field=models.SlugField(unique=True),
        ),
        migrations.AddIndex(
            model_name='serviceinstance',
            index=models.Index(fields=['owner', 'service_type'], name='api_service_owner_i_e993b8_idx'),
        ),
        migrations.DeleteModel(
            name='GroupBusinessRule',
        ),
        migrations.DeleteModel(
            name='ServiceApp',
        ),
    ]
