# Generated by Django 5.0 on 2026-03-09 23:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_remove_groupbusinessrule_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceApp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('app_slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('default_state_config', models.JSONField(blank=True, default=dict)),
                ('default_app_data', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owners', models.ManyToManyField(related_name='owned_apps', to=settings.AUTH_USER_MODEL)),
                ('template_source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.servicetemplate')),
            ],
        ),
    ]
