# Generated by Django 5.0 on 2026-03-14 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_serviceapp'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceinstance',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text="Se vero, l'istanza viene nascosta dalla dashboard pur rimanendo attiva e di proprietà dell'utente."),
        ),
    ]
